=== CR1337/quiz-webapp/data/questions-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "index",
            "type",
            "text",
            "explanation",
            "image",
            "image_caption",
            "coupled_question_indices"
        ],
        "properties": {
            "index": {
                "type": "integer"
            },
            "unit": {
                "type": "object",
                "required": [
                    "de",
                    "en"
                ],
                "properties": {
                    "de": {
                        "type": [
                            "string",
                            "null"
                        ]
                    },
                    "en": {
                        "type": [
                            "string",
                            "null"
                        ]
                    }
                },
                "additionalProperties": true
            },
            "type": {
                "type": "string",
                "enum": [
                    "multiple_choice",
                    "guess"
                ]
            },
            "text": {
                "type": "object",
                "required": [
                    "de",
                    "en"
                ],
                "properties": {
                    "de": {
                        "type": "string"
                    },
                    "en": {
                        "type": "string"
                    }
                },
                "additionalProperties": true
            },
            "explanation": {
                "type": "object",
                "required": [
                    "de",
                    "en"
                ],
                "properties": {
                    "de": {
                        "type": "string"
                    },
                    "en": {
                        "type": "string"
                    }
                },
                "additionalProperties": true
            },
            "image": {
                "type": "object",
                "required": [
                    "de",
                    "en"
                ],
                "properties": {
                    "de": {
                        "type": "string"
                    },
                    "en": {
                        "type": "string"
                    }
                },
                "additionalProperties": true
            },
            "image_caption": {
                "type": "object",
                "required": [
                    "de",
                    "en"
                ],
                "properties": {
                    "de": {
                        "type": [
                            "string",
                            "null"
                        ]
                    },
                    "en": {
                        "type": [
                            "string",
                            "null"
                        ]
                    }
                },
                "additionalProperties": true
            },
            "answers": {
                "type": "object",
                "required": [
                    "de",
                    "en"
                ],
                "properties": {
                    "de": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "en": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "additionalProperties": true
            },
            "right_answer_index": {
                "type": "integer",
                "minimum": 0
            },
            "answer": {
                "type": "number"
            },
            "max_points": {
                "type": "integer",
                "minimum": 0
            },
            "min_guess": {
                "type": "number"
            },
            "max_guess": {
                "type": "number"
            },
            "coupled_question_indices": {
                "type": "array",
                "items": {
                    "type": "integer"
                }
            }
        },
        "allOf": [
            {
                "if": {
                    "properties": {
                        "type": {
                            "const": "multiple_choice"
                        }
                    }
                },
                "then": {
                    "required": [
                        "answers",
                        "right_answer_index"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "const": "guess"
                        }
                    }
                },
                "then": {
                    "required": [
                        "answer",
                        "max_points",
                        "unit"
                    ]
                }
            }
        ],
        "additionalProperties": true
    }
}

=== CR1337/quiz-webapp/data/questions.json
[
    {
        "index": 0,
        "unit": {
            "de": "EU-Staaten",
            "en": "EU countries"
        },
        "type": "guess",
        "text": {
            "de": "In wie vielen EU-Staaten lief der Zensus bei der letzen Zensusrunde 2021/2022 ohne Befragung, also nur auf Basis von Registern?",
            "en": "In how many EU countries was the 2021/2022 census conducted without interviews—that is, based solely on official records?"
        },
        "answer": 10,
        "min_guess": 0,
        "max_guess": 27,
        "max_points": 10,
        "explanation": {
            "de": "In 10 EU-Staaten wurde der Zensus bei der letzten Zensusrunde 2021/22 ohne Befragung, also nur auf Basis von Registern, durchgeführt.",
            "en": "In 10 EU countries, the census during the 2021/22 round was conducted without surveys, using only official records."
        },
        "image": {
            "de": "EU_Sterne.png",
            "en": "EU_Sterne.png"
        },
        "image_caption": {
            "de": null,
            "en": null
        },
        "coupled_question_indices": []
    },
    {
        "index": 1,
        "unit": {
            "de": "Tausend Interviewende",
            "en": "Thousand Interviewers"
        },
        "type": "guess",
        "text": {
            "de": "Wie viele Interviewende wurden ungefähr beim Zensus 2022 eingesetzt?",
            "en": "Approximately how many interviewers were deployed for the 2022 census?"
        },
        "answer": 100,
        "min_guess": 10,
        "max_guess": 200,
        "max_points": 10,
        "explanation": {
            "de": "Ungefähr 100.000 Interviewende wurden beim Zensus 2022 eingesetzt.",
            "en": "Approximately 100,000 interviewers were deployed during the 2022 census."
        },
        "image": {
            "de": "Befragung.png",
            "en": "Befragung.png"
        },
        "image_caption": {
            "de": null,
            "en": null
        },
        "coupled_question_indices": []
    },
    {
        "index": 2,
        "unit": {
            "de": "%",
            "en": "%"
        },
        "type": "guess",
        "text": {
            "de": "Beim Zensus 2022 mussten alle Eigentümer/-innen Angaben zur Gebäude- und Wohnungszählung machen. Welcher Anteil der Eigentümer/-innen meldete die Daten online?",
            "en": "For the 2022 census, all property owners were required to provide information for the building and housing census. What percentage of property owners submitted their data online?"
        },
        "answer": 82,
        "min_guess": 0,
        "max_guess": 100,
        "max_points": 10,
        "explanation": {
            "de": "Im Zensus 2022 wurden 82 Prozent der Fragebögen der Gebäude- und Wohnungszählung online übermittelt.",
            "en": "In the 2022 census, 82 percent of the building and housing census questionnaires were submitted online."
        },
        "image": {
            "de": "Zuhause_Privates_Büro_Gaming.png",
            "en": "Zuhause_Privates_Büro_Gaming.png"
        },
        "image_caption": {
            "de": null,
            "en": null
        },
        "coupled_question_indices": []
    },
    {
        "index": 3,
        "unit": {
            "de": "Millionen Personen",
            "en": "Million inhabitants"
        },
        "type": "guess",
        "text": {
            "de": "Wie hat sich die Bevölkerungszahl vom Zensus 2011 bis zum Zensus 2022 entwickelt?",
            "en": "How did the population change between the 2011 census and the 2022 census?"
        },
        "answer": 2.5,
        "min_guess": -8,
        "max_guess": 8,
        "max_points": 10,
        "explanation": {
            "de": "Laut Zensus 2022 lebten 2,5 Millionen mehr Einwohnerinnen und Einwohner in Deutschland als zum Zensus 2011.",
            "en": "According to the 2022 census, Germany's population increased by 2.5 million inhabitants compared to the 2011 census."
        },
        "image": {
            "de": "Park_Umwelt_Soziales.png",
            "en": "Park_Umwelt_Soziales.png"
        },
        "image_caption": {
            "de": null,
            "en": null
        },
        "coupled_question_indices": []
    },
    {
        "index": 4,
        "unit": {
            "de": "m²",
            "en": "m²"
        },
        "type": "guess",
        "text": {
            "de": "Wie groß war die durchschnittliche Wohnung in Deutschland laut Zensus im Jahr 2022?",
            "en": "According to the 2022 census, what was the average size of an apartment in Germany?"
        },
        "answer": 94.4,
        "min_guess": 30,
        "max_guess": 150,
        "max_points": 10,
        "explanation": {
            "de": "Die durchschnittliche Größe von Wohnungen in Deutschland betrug laut dem Zensus 2022 94,4 m².",
            "en": "According to the 2022 census, the average size of apartments in Germany was 94.4 square meters."
        },
        "image": {
            "de": "Zuhause_Privates_Büro_Gaming.png",
            "en": "Zuhause_Privates_Büro_Gaming.png"
        },
        "image_caption": {
            "de": null,
            "en": null
        },
        "coupled_question_indices": []
    },
    {
        "index": 5,
        "unit": {
            "de": "%",
            "en": "%"
        },
        "type": "guess",
        "text": {
            "de": "Wie hoch war die beim Zensus 2022 ermittelte Erwerbstätigenquote in Deutschland?",
            "en": "What was the employment rate in Germany as determined by the 2022 census?"
        },
        "answer": 75.7,
        "min_guess": 0,
        "max_guess": 100,
        "max_points": 10,
        "explanation": {
            "de": "Die beim Zensus 2022 ermittelte Erwerbstätigenquote in Deutschland betrug 75,7%.",
            "en": "The employment rate in Germany as determined by the 2022 census was 75.7%."
        },
        "image": {
            "de": "Wirtschaft_Unternehmen.png",
            "en": "Wirtschaft_Unternehmen.png"
        },
        "image_caption": {
            "de": null,
            "en": null
        },
        "coupled_question_indices": []
    },
    {
        "index": 6,
        "unit": {
            "de": "%",
            "en": "%"
        },
        "type": "guess",
        "text": {
            "de": "Welcher Anteil an Menschen im Rentenalter war laut Zensus 2022 noch erwerbstätig?",
            "en": "According to the 2022 census, what percentage of people of retirement age were still employed?"
        },
        "answer": 10.1,
        "min_guess": 0,
        "max_guess": 40,
        "max_points": 10,
        "explanation": {
            "de": "Laut Zensus 2022 waren 10,1 % der Menschen im Rentenalter noch erwerbstätig.",
            "en": "According to the 2022 census, 10.1 % of people at retirement age were still employed."
        },
        "image": {
            "de": "Älter.png",
            "en": "Älter.png"
        },
        "image_caption": {
            "de": null,
            "en": null
        },
        "coupled_question_indices": []
    },
    {
        "index": 7,
        "type": "multiple_choice",
        "text": {
            "de": "Welcher Energieträger wurde laut Zensus 2022 in Deutschland am häufigsten zur Beheizung von Wohnungen genutzt?",
            "en": "According to the 2022 census, which energy source was most commonly used for heating homes in Germany?"
        },
        "answers": {
            "de": ["Gas", "Heizöl", "Fernwärme", "Holz/Holzpellets"],
            "en": ["Natural gas", "Heating oil", "District heating", "Wood/wood pellets"]
        },
        "right_answer_index": 0,
        "scores": [10, 2, 3, 1],
        "explanation": {
            "de": "Laut Zensus 2022 war Gas der meistgenutzte Energieträger für die Heizung von Wohnungen in Deutschland (56 %), gefolgt von Heizöl (19 %), Fernwärme (15 %) und Holz/Holzpellets (4 %).",
            "en": "According to the 2022 census, natural gas was the most commonly used energy source for heating apartments in Germany (56 %), followed by heating oil (19 %), district heating (15 %), and wood/wood pellets (4 %)."
        },
        "image": {
            "de": "Wohnung_Heizkörper.png",
            "en": "Wohnung_Heizkörper.png"
        },
        "image_caption": {
            "de": null,
            "en": null
        },
        "coupled_question_indices": []
    },
    {
        "index": 8,
        "unit": {
            "de": "%",
            "en": "%"
        },
        "type": "guess",
        "text": {
            "de": "Wie hoch war laut Zensus 2022 der Anteil der Wohnungen mit Gasheizung in Deutschland?",
            "en": "According to the 2022 census, what percentage of apartments in Germany had gas heating?"
        },
        "answer": 56,
        "min_guess": 0,
        "max_guess": 100,
        "max_points": 10,
        "explanation": {
            "de": "Laut Zensus 2022 betrug der Anteil der Wohnungen mit Gasheizung in Deutschland 56%.",
            "en": "According to the 2022 census, 56% of apartments in Germany used gas heating."
        },
        "image": {
            "de": "Wohnung_Heizkörper.png",
            "en": "Wohnung_Heizkörper.png"
        },
        "image_caption": {
            "de": null,
            "en": null
        },
        "coupled_question_indices": []
    },
    {
        "index": 9,
        "type": "multiple_choice",
        "text": {
            "de": "In welcher deutschen Großstadt war laut Zensus 2022 die durchschnittliche Nettokaltmiete pro m² am niedrigsten?",
            "en": "In which German major city was the average net cold rent per m² the lowest, according to census 2022?"
        },
        "answers": {
            "de": ["Chemnitz", "Gelsenkirchen", "Hagen", "Bremerhaven"],
            "en": ["Chemnitz", "Gelsenkirchen", "Hagen", "Bremerhaven"]
        },
        "right_answer_index": 0,
        "scores": [10, 3, 5, 1],
